language: python
python:
  - 3.4
  - 3.5
  - 3.6

cache: pip

addons:
  apt:
    packages:
      - libssl-dev
      - python3-dev

before_install:
  - cat test-requirements.txt >> requirements.txt
  - npm install stylelint@7 -g

script:
  - python -m pytest -vv
  - coala --non-interactive -V

after_failure:
  - tail -n +1 -- static/errors/*.dump

notifications:
  email: false
